### ISSUE TITLE
Make a Donate Button

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#10]
Make a Donate Button and Link it with the Website Donate Page

**Comment by joshijoe05** [comment]
Hello,
I would like to work on this issue.. 
Can you assign this task to me?
And also provide the link of the donate page and the location where donate button should be placed

**Comment by aviralsingh108** [comment]
@joshijoe05 Sure, I have added the link, please check the latest code, try to make the donate button round, add a heart with the text - 'Donate ♥' and change the background color to red
