### ISSUE TITLE
Make the top header static

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#12]
Make the top header static, when we click on a link the header should be static and the new link or page should load below it

**Comment by vanshika8750** [comment]
i want to do this. please assign it to me

**Comment by aviralsingh108** [comment]
@joshijoe05 yeah sticky navbar

**Comment by aviralsingh108** [comment]
@vanshika8750 I've added a couple more small things, just in case they might be of interest.

**Comment by joshijoe05** [comment]
Can you please assign this to me?
