### ISSUE TITLE
Align the header buttons

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#15]
Align the Home, Contact and About Us to the center and Donate button to the right only, but with some padding.
Also add Padding for the Logo and decrease the height of the entire Header. 
Pick some suitable background color for the page!
![image](https://github.com/aviralsingh108/khwaahishBirthday/assets/53104755/2e189bfc-b78a-44a5-9235-a8d318849cfa)

**Comment by ayu5hagarwal** [comment]
I can do it,can you assign me the issue.

**Comment by ayu5hagarwal** [comment]
file:///home/warndarkahead/Pictures/header.png

**Comment by ayu5hagarwal** [comment]
![header](https://github.com/aviralsingh108/khwaahishBirthday/assets/116223165/a11d1f58-a693-4299-b33b-a6c0ff900376)
