### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#16]
Add a Favicon for the Website like this - 
![image](https://github.com/aviralsingh108/khwaahishBirthday/assets/53104755/276771fc-9860-4637-a6b7-163e8505d9b1)

Favicon - A favicon is a small icon that appears in the browser's tab or window title bar and is typically used to represent a website or webpage.

**Comment by giovannism20** [comment]
I'll do this!

**Comment by aviralsingh108** [comment]
@giovannism20 Sure, would be useful

**Comment by adityakhevaria** [comment]
I would like to contribute to your repository. Assign me this
