### ISSUE TITLE
Clicking on Contact, About and Donate button should open the page below the header

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#29]
Clicking on Contact, About and Donate button should open the page below the header. 
Note - Contact Us Page is added with a New Header which can be removed once this issue is fixed

**Comment by vivek-dhiman** [comment]
Please assign this issue to me.

**Comment by Git-Akshat01** [comment]
Hi! @aviralsingh108 please assign this task to me

**Comment by prattsss** [comment]
hey! @aviralsingh108 
Though it is very possible with just HTML and JS to render the pages without reloading... code is repeated a lot 
I'd suggest moving this into a react js project.
It will be much faster and easier to work on it.
If you just want to have it in a general way, we can just do it with anchor tags and adding the navbar and footer to other pages as well.

**Comment by aviralsingh108** [comment]
Hi @prattsss,

I want to express my appreciation for your suggestion. This page was primarily created by young children with my guidance as their mentor. At this point, I am making some minor adjustments and creating simple issues to help individuals become acquainted with GitHub and the overall development process.

I've observed that embarking on open-source contributions can be challenging when starting with larger projects. By beginning with smaller contributions and becoming comfortable with the process, individuals can gain the confidence needed to make a meaningful impact on more substantial projects in the future.

Please let me know if you would like to continue working on this issue as well!

**Comment by aviralsingh108** [comment]
@Git-Akshat01 Sure, I have assigned it

**Comment by Git-Akshat01** [comment]
Thanks @aviralsingh108 will be submitting the task ASAP.

**Comment by aviralsingh108** [comment]
Anyone interested can take up the issue

**Comment by Mohitbagul** [comment]
Hello sir,I wanted to know some extra information to work on this PR.
Sir in this PR are you asking to connect the **Youtube page** to Contact,About,Donate buttons?
