### ISSUE TITLE
Add a CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#3]
Add a CONTRIBUTING.md file  with contribution guidelines to your repository, and code of conduct.

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can you assign me this issue.

**Comment by aviralsingh108** [comment]
@Durgeshsejekar , Hi assigning a new Issue to add the logo, kindly check from the issue list and create a PR for it, thanks!
