### ISSUE TITLE
want to remove scroll bar from the web site for the better appearance of web Site 

### ISSUE THREAD

**Issue by pra9patil** [aviralsingh108/khwaahishBirthday#35]
Hey Khwaahish team 
I just want to remove that scroll bar from the right most side of the web site 
using simple html and css 
Will you please assign me this issue under hactoberfest

**Comment by aviralsingh108** [comment]
Sure, @pra9patil Please, attach a screenshot of the changes in the PR as well.

**Comment by pra9patil** [comment]
Sure Sir , I will
