### ISSUE TITLE
Change the Company Logo, to existing Logo

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#5]
Change the Company Logo, to existing Logo of Khwaahish, as shown below
![Capture](https://github.com/aviralsingh108/khwaahishBirthday/assets/53104755/4cee5407-d2b2-4873-8af4-fe99dcb36593)

**Comment by ghOst-vedant** [comment]
@aviralsingh108 can u assign this to me

**Comment by Shubhamgulik** [comment]
Hi @aviralsingh108, can you please assign this to me. I understand what the issue is and how to proceed to resolve issue.

**Comment by Parmesh119** [comment]
Hi @aviralsingh108, I am Parmesh B.
I hope you are fine.
Can you assign this issue to me?

**Comment by aviralsingh108** [comment]
Hi @Shubhamgulik @Parmesh119  , this issue is completed, you can check this one if you find it interesting - https://github.com/aviralsingh108/khwaahishBirthday/issues/6
