### ISSUE TITLE
Add a Contact Page

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#6]
Add a Contact Page and Link it with the contact tab in the header
Use the below website to fill in the demo data for contact us page, you can pick up the Google Maps Address if the Phone no is not given.
Website - https://www.khwaahish.in/

**Comment by ApurvaBasule** [comment]
@aviralsingh108 can you assign it to me

**Comment by aviralsingh108** [comment]
@ApurvaBasule  Yeah assigned, use the below website to fill in the demo data for contact us page, you can pick up the Google Maps Address if the Phone no is not given.
Website - https://www.khwaahish.in/

**Comment by shbd845** [comment]
Hello @aviralsingh108 , i can add the contact page.Can you please assign this  issue to me?
I am thinking of creating fields along with your google map location.
![image](https://github.com/aviralsingh108/khwaahishBirthday/assets/88442935/d22bff70-0bff-4c8c-b0f2-1f38d4e9b1d4)

The Design format will be similar to that of your website ,the image is just for reference purposes.

**Comment by aviralsingh108** [comment]
Hi @shbd845 I have assigned it to you!
