### ISSUE TITLE
Add a About Page

### ISSUE THREAD

**Issue by aviralsingh108** [aviralsingh108/khwaahishBirthday#7]
Add a About Page and Link it with the About tab in the header

**Comment by vanshika8750** [comment]
i want to do this . please assign it to me

**Comment by aviralsingh108** [comment]
@vanshika8750 About us Page is added, try to beautify the content and centre the heading, as suitable
![about](https://github.com/aviralsingh108/khwaahishBirthday/assets/53104755/ee1f5fb0-5fb1-485c-a435-bdb0d6d13014)
